name: Deploy to Render (PR check)

on:
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Render deploy
        id: deploy
        run: |
          response=$(curl -s -X POST \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{}' \
            https://api.render.com/v1/services/srv-d3e2rauuk2gs739rlrfg/deploys)

          echo "Deploy triggered: $response"
          deploy_id=$(echo "$response" | jq -r '.id')
          if [ "$deploy_id" = "null" ] || [ -z "$deploy_id" ]; then
          echo "❌ Failed to get deploy_id from Render response"
          exit 1
          fi
          
          echo "deploy_id=$deploy_id" >> $GITHUB_ENV

      - name: Wait for Render deploy to finish
        run: |
          status="in_progress"
          while [ "$status" = "in_progress" ] || [ "$status" = "pending" ]; do
            sleep 15
            response=$(curl -s \
              -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
              https://api.render.com/v1/deploys/$deploy_id)

            status=$(echo "$response" | jq -r '.status')
            echo "Current status: $status"
          done

          if [ "$status" != "live" ]; then
            echo "❌ Render deploy failed: $status"
            exit 1
          fi

          echo "✅ Render deploy successful"
